name: Build and Push FE & Node to ECR and Deploy to ECS

on:
  push:
    branches: [master]

#For The Backend Application
jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Necessary for OIDC 
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Check if backend changed
        id: backend_changed
        uses: tj-actions/changed-files@v41
        with:
          files: |
            Node/**
            backend-task.json

      - name: Configure AWS credentials
        if: steps.backend_changed.outputs.any_changed == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1 #example

      - name: Login to ECR
        if: steps.backend_changed.outputs.any_changed == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Backend
        if: steps.backend_changed.outputs.any_changed == 'true'
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/repo-name:backend-tag"
          docker build -t $IMAGE_URI -f Node/Dockerfile ./Node
          docker push $IMAGE_URI

      - name: Backend Task Definition
        if: steps.backend_changed.outputs.any_changed == 'true'
        id: render-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: backend-task.json
          container-name: container-name
          image: ${{ steps.login-ecr.outputs.registry }}/repo-name:backend-tag

      - name: Deploy Backend to ECS
        if: steps.backend_changed.outputs.any_changed == 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-backend.outputs.task-definition }}
          service: service-name
          cluster: cluster-name
          wait-for-service-stability: false
#For The Front End Application
  frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # 
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Check if frontend changed
        id: frontend_changed
        uses: tj-actions/changed-files@v41
        with:
          files: |
            FE/**
            frontend-task.json

      - name: Configure AWS credentials
        if: steps.frontend_changed.outputs.any_changed == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Login to ECR
        if: steps.frontend_changed.outputs.any_changed == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Frontend
        if: steps.frontend_changed.outputs.any_changed == 'true'
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/repo-name:frontend-tag"
          docker build -t $IMAGE_URI -f FE/Dockerfile ./FE
          docker push $IMAGE_URI

      - name: Frontend Task Definition
        if: steps.frontend_changed.outputs.any_changed == 'true'
        id: render-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-defination-name.json
          container-name: container-name
          image: ${{ steps.login-ecr.outputs.registry }}/repo-name:frontend-tag

      - name: Deploy Frontend to ECS
        if: steps.frontend_changed.outputs.any_changed == 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-frontend.outputs.task-definition }}
          service: service-name
          cluster: cluster-name
          wait-for-service-stability: false
