name: Deploy Application to AWS ECS (Fargate)

on:
push:
branches:
- main
paths:
- 'backend/**'
- 'frontend/**'

env:
AWS_REGION: region
ECR_REPOSITORY: Repo-Name
ECS_CLUSTER: Cluster-Name
FRONTEND_SERVICE: frontend-service-name
BACKEND_SERVICE: backend-service-name

jobs:
deploy:
name: Build & Deploy (Selective)
runs-on: ubuntu-latest

```
steps:
  - name: Checkout source code
    uses: actions/checkout@v4

  - name: Detect changed paths
    id: changes
    uses: dorny/paths-filter@v3
    with:
      filters: |
        backend:
          - 'backend/**'
        frontend:
          - 'frontend/**'

  - name: Configure AWS credentials
    if: steps.changes.outputs.backend == 'true' || steps.changes.outputs.frontend == 'true'
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION }}

  - name: Login to Amazon ECR
    if: steps.changes.outputs.backend == 'true' || steps.changes.outputs.frontend == 'true'
    uses: aws-actions/amazon-ecr-login@v2

  # ---------- BACKEND ----------
  - name: Build & Push Backend Image
    if: steps.changes.outputs.backend == 'true'
    run: |
      docker build -t $ECR_REPOSITORY:backend ./backend
      docker tag $ECR_REPOSITORY:backend ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:backend
      docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:backend

  - name: Deploy Backend to ECS
    if: steps.changes.outputs.backend == 'true'
    run: |
      aws ecs update-service \
        --cluster $ECS_CLUSTER \
        --service $BACKEND_SERVICE \
        --force-new-deployment

  # ---------- FRONTEND ----------
  - name: Build & Push Frontend Image
    if: steps.changes.outputs.frontend == 'true'
    run: |
      docker build -t $ECR_REPOSITORY:frontend ./frontend
      docker tag $ECR_REPOSITORY:frontend ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:frontend
      docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:frontend

  - name: Deploy Frontend to ECS
    if: steps.changes.outputs.frontend == 'true'
    run: |
      aws ecs update-service \
        --cluster $ECS_CLUSTER \
        --service $FRONTEND_SERVICE \
        --force-new-deployment
```
